---
alle_lichten:
  name: Alle Lichten
  entities:
    - light.zolder
    - light.slaapkamer
    - light.slaapkamer_elyza
    - switch.schakelaar_santi
    - light.wled_elyza
    - light.wled_santi
    - light.kelder
    - light.toilet_licht
    - light.woonkamer_spotjes
    - light.keuken
    - switch.keuken_schakelaar
    - switch.kast
    - light.tuin_groep
