---
alle_ramen:
  name: Alle Ramen
  entities:
    - binary_sensor.badkamer_raam
    - binary_sensor.slaapkamer_raam
    - binary_sensor.slaapkamer_raam_santi
    - binary_sensor.slaapkamer_raam_elyza
