---
blueprint:
  name: ZHA - IKEA wireless on/off switch
  description: Control anything using IKEA wireless on/off switch
  domain: automation
  input:
    remote:
      name: Remote
      description: IKEA wireless on/off switch to use
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI on/off switch
    button_on_short:
      name: On button press
      description: Action to run on press of On button
      default: []
      selector:
        action: {}
    button_off_short:
      name: Off button press
      description: Action to run on press of Off button
      default: []
      selector:
        action: {}
    button_on_long:
      name: On button hold
      description: Action to run on long press of On button
      default: []
      selector:
        action: {}
    button_off_long:
      name: Off button hold
      description: Action to run on long press of Off button
      default: []
      selector:
        action: {}
  source_url: https://community.home-assistant.io/t/zha-ikea-tradfri-on-off-switch/255538
mode: restart
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input 'remote'
action:
  - variables:
      command: '{{ trigger.event.data.command }}'
      cluster_id: '{{ trigger.event.data.cluster_id }}'
      endpoint_id: '{{ trigger.event.data.endpoint_id }}'
      args: '{{ trigger.event.data.args }}'
  - choose:
      - conditions:
          - '{{ command == ''on'' }}'
          - '{{ cluster_id == 6 }}'
          - '{{ endpoint_id == 1 }}'
        sequence: !input 'button_on_short'
      - conditions:
          - '{{ command == ''off'' }}'
          - '{{ cluster_id == 6 }}'
          - '{{ endpoint_id == 1 }}'
        sequence: !input 'button_off_short'
      - conditions:
          - '{{ command == ''move_with_on_off'' }}'
          - '{{ cluster_id == 8 }}'
          - '{{ endpoint_id == 1 }}'
          - '{{ args == [0, 83] }}'
        sequence: !input 'button_on_long'
      - conditions:
          - '{{ command == ''move'' }}'
          - '{{ cluster_id == 8 }}'
          - '{{ endpoint_id == 1 }}'
          - '{{ args == [1, 83] }}'
        sequence: !input 'button_off_long'
