---
- platform: group
  name: Tuin Led Groep
  entities:
    - light.tuin_led_1
    - light.tuin_led_2
    - light.tuin_led_3
    - light.tuin_led_4
- platform: group
  name: Patio
  entities:
    - light.patio_led_1
    - light.patio_led_2
    - light.patio_led_3
    - light.patio_led_4
    - light.patio_led_5
    - light.patio_led_6
- platform: group
  name: Woonkamer Spotjes
  entities:
    - light.woonkamer_spotjes_1
    - light.woonkamer_spotjes_2
- platform: group
  name: Zolder
  entities:
    - light.zolder_licht_1
    - light.zolder_licht_2
- platform: group
  name: Tuin
  entities:
    - light.patio
    - light.tuin_led_groep
    - light.kleine_schuur
    - light.schuur
    - light.groot_licht
    - light.schuur_led
