input_boolean.heating_boost:
  device_class: heat
binary_sensor.bathroom_window_sensor:
  device_class: window
binary_sensor.boys_room_window_sensor:
  device_class: window
  friendly_name: Boys Room Window
binary_sensor.girls_room_window_sensor:
  device_class: window
  friendly_name: Girls Room Window
binary_sensor.master_bedroom_sensor:
  device_class: window
  friendly_name: Master Bedroom Window
binary_sensor.door_sensor_back:
  device_class: door
  friendly_name: Back Door
binary_sensor.door_sensor_front:
  device_class: door
  friendly_name: Front Door
input_boolean.rolluik:
  device_class: garage_door
switch.keuken_schakelaar_relay:
  friendly_name: Keuken Spotjes
sensor.multi_sensor_beneden_temperatuur:
  friendly_name: Beneden Temperatuur
climate.woonkamer:
  friendly_name: Thermostaat
switch.schakelaar_santi_relay:
  friendly_name: Spotjes Santi
sensor.multi_upstairs_temp:
  friendly_name: Boven Temperatuur
