---
substitutions:
  devicename: keuken_schakelaar
  upper_devicename: Keuken Schakelaar

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  ap:
    ssid: keuken_schakelaar
    password: keuken1234

captive_portal:

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    name: "$upper_devicename Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
    internal: true
    on_multi_click:
    # single
      - timing:
        - ON for at most 1s
        - OFF for at least 1s
        then:
          - switch.toggle: relay
    # double
      - timing:
        - ON for at most 1s
        - OFF for at most 0.5s
        - ON for 0.5s to 1s
        - OFF for at least 0.2s
        then:
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.keuken
    # hold
      - timing:
        - ON for 1s to 5s
        - OFF for at least 0.5s
        then:
          - homeassistant.service:
              service: light.toggle
              data:
                entity_id: light.tuin

output:
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: 'true'

light:
  - platform: monochromatic
    name: "$upper_devicename Wifi LED"
    output: blue_led
    internal: true
    id: blue_led_light

switch:
  - platform: gpio
    id: relay
    pin: GPIO12
    name: "$upper_devicename Relay"

text_sensor:
  - platform: version
    name: "$upper_devicename ESPHome Version"
    hide_timestamp: 'true'
