---
substitutions:
  devicename: toilet_light
  upper_devicename: Toilet Licht

esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_passwd
  ap:
    ssid: toilet_light
    password: toilet1234

captive_portal:

web_server:
  port: 80

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: 'true'
    on_press:
      - light.toggle: $devicename

output:
  - platform: gpio
    id: light_relay
    pin: GPIO12

light:
  - platform: binary
    id: $devicename
    name: $upper_devicename
    output: light_relay

text_sensor:
  - platform: version
    name: "ESPHome Version"
    hide_timestamp: 'true'
