- platform: brandstofprijzen
  monitored_variables:
    - euro95
    - diesel
    - lpg
    - super
    - super_mlv
    - premium_benzines
    - premium_diesels
    - blueone95
  icon: mdi:gas-station
  unit_of_measurement: €/L
  prefix: Adviesprijs
  scan_interval:
      hours: 1
