---
- platform: command_line
  name: Supervisor updates
  command: 'curl http://supervisor/supervisor/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version,"update_available":.data.update_available,"addons":[.data.addons[] | select(.update_available)]}'''
  value_template: "{{ value_json.addons | length }}"
  unit_of_measurement: pending update(s)
  json_attributes:
  - update_available
  - newest_version
  - current_version
  - addons
- platform: command_line
  name: Updater Audio
  command: 'curl http://supervisor/audio/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
  value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
  json_attributes:
  - update_available
  - newest_version
  - current_version
- platform: command_line
  name: Updater DNS
  command: 'curl http://supervisor/dns/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
  value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
  json_attributes:
  - update_available
  - newest_version
  - current_version
- platform: command_line
  name: Updater CLI
  command: 'curl http://supervisor/cli/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
  value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
  json_attributes:
  - update_available
  - newest_version
  - current_version
- platform: command_line
  name: Updater Multicast
  command: 'curl http://supervisor/multicast/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
  value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
  json_attributes:
  - update_available
  - newest_version
  - current_version
- platform: command_line
  name: Updater Observer
  command: 'curl http://supervisor/observer/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
  value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
  json_attributes:
  - update_available
  - newest_version
  - current_version
# Alternate updater sensor for core since binary_sensor.updater is very slow to recognize updates
- platform: command_line
  name: Updater Core
  command: 'curl http://supervisor/core/info -H "Authorization: Bearer $(printenv SUPERVISOR_TOKEN)" | jq ''{"newest_version":.data.version_latest,"current_version":.data.version, "update_available":.data.update_available}'''
  value_template: "{% if value_json.update_available %}on{% else %}off{% endif %}"
  json_attributes:
  - update_available
  - newest_version
  - current_version
